/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.caj;

import controller.ClientController;
import domain.Caj;
import forms.FrmMode;
import forms.MainForm;
import javax.swing.JOptionPane;
import models.TableModelCaj;


/**
 *
 * @author Yo
 */
public class InsertUpdateCajDialog extends javax.swing.JDialog
{

    private FrmMode currentMode;
    private Caj caj;

    /**
     * Creates new form NoviKupacDijalog
     */
    public InsertUpdateCajDialog(java.awt.Frame parent, boolean modal, FrmMode mode)
    {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(parent);
        currentMode = mode;
        prepareDialog();

    }

    public InsertUpdateCajDialog(java.awt.Dialog parent, boolean modal, FrmMode mode, Caj caj)
    {
        super(parent, modal);
        initComponents();

        currentMode = mode;
        this.caj = caj;

        prepareDialog();
        setLocationRelativeTo(null);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        btnAction = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taManual = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Naziv");

        tfName.setPreferredSize(new java.awt.Dimension(222, 22));

        jLabel5.setText("Cena");

        tfPrice.setPreferredSize(new java.awt.Dimension(222, 22));

        btnAction.setText("Sačuvaj");
        btnAction.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionActionPerformed(evt);
            }
        });

        lblID.setText("ID");

        tfID.setPreferredSize(new java.awt.Dimension(222, 22));

        jLabel4.setText("Korisničko uputsvo");

        taManual.setColumns(20);
        taManual.setRows(5);
        jScrollPane1.setViewportView(taManual);

        jLabel6.setText("Opis");

        taDescription.setColumns(20);
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(lblID)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(tfID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnAction)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnActionActionPerformed
    {//GEN-HEADEREND:event_btnActionActionPerformed
        Caj c = checkInputs();
        if (c == null)
        {
            return;
        }
        
        if (currentMode == FrmMode.UPDATE)
        {
            try
            {
                ClientController.getInstance().updateCaj(caj);
                JOptionPane.showMessageDialog(this, "Izmene su uspešno sačuvane.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
                
                SearchCajDialog scd = (SearchCajDialog) getParent();
                ((TableModelCaj) scd.getTblCajevi().getModel()).refresh();
                
                this.dispose();
            }
            catch (Exception ex)
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Greska!\n" + ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if (currentMode == FrmMode.ADD)
        {
            try
            {
                Caj caj = ClientController.getInstance().addCaj(c);
                int option = JOptionPane.showConfirmDialog(this, "Caj: " + caj.toString() + " je uspešno dodat sa ID-jem " + caj.getIdCaj() 
                        + ".\n želite li da dodate još jedan? ", 
                        "Poruka", JOptionPane.YES_NO_OPTION);
                
                MainForm mf = (MainForm) getParent();
                mf.populateCajCombo();
                
                if (option == JOptionPane.NO_OPTION)
                    this.dispose();
                else if (option == JOptionPane.YES_OPTION)
                    clearInput();
            }
            catch (Exception ex)
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Greška!\n" + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnActionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextArea taManual;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables

    private Caj checkInputs()
    {
        String name = tfName.getText().strip();
        String price = tfPrice.getText().strip();
        String manual = taManual.getText();
        String description = taDescription.getText();

        if (!validateName(name))
        {
            tfName.setText("");
            return null;
        }
        
        if (!validatePrice(price))
        {
            tfPrice.setText("");
            return null;
        }

        String formattedName = capitalize(name);
        double formattedPrice = Double.valueOf(price);
        
        
        if (caj != null)
        {
            caj.setNaziv(formattedName);
            caj.setCena(formattedPrice);
            caj.setKorisnickoUputstvo(manual);
            caj.setOpis(description);
            
            return caj;
        }
        
        return new Caj(formattedName, formattedPrice, manual, description);
    }



    private void prepareDialog()
    {
        tfID.setEnabled(false);

        if (currentMode == FrmMode.ADD)
        {
            tfID.setVisible(false);
            lblID.setVisible(false);

            btnAction.setText("Dodaj");
            setTitle("Dijalog - Novi čaj");
        }
        else if (currentMode == FrmMode.UPDATE)
        {
            btnAction.setText("Izmeni");
            setTitle("Dijalog - Izmeni čaj");

            tfID.setText(String.valueOf(caj.getIdCaj()));
            tfName.setText(caj.getNaziv());
            tfPrice.setText(String.valueOf(caj.getCena()));
            taManual.setText(caj.getKorisnickoUputstvo());
            taDescription.setText(caj.getOpis());
            
        }
        else
        {
            System.err.println("NEPOSTOJECI MODE!");
        }
    }

    private boolean validateName(String name)
    {
        if (name == null || name.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Naziv ne sme biti prazan!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (name.length() > 30)
        {
            JOptionPane.showMessageDialog(this, "Naziv ne sme imati više od 30 karaktera!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private boolean validatePrice(String price)
    {
        if (price == null || price.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Cena ne sme biti prazna!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try
        {
            Double.valueOf(price);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Morate uneti ispravan broj!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }

    
    private String capitalize(String str)
    {
        if (str == null || str.isEmpty())
        {
            return str;
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }

    private void clearInput()
    {
        tfName.setText("");
        tfPrice.setText("");
        taDescription.setText("");
        taManual.setText("");
    }
}
