/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.caj;

import controller.ClientController;
import domain.Caj;
import forms.FrmMode;
import forms.MainForm;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelCaj;

/**
 *
 * @author Yo
 */
public class SearchCajDialog extends javax.swing.JDialog
{

    /**
     * Creates new form PretragaCajaDijalog
     */
    public SearchCajDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        tblCajevi.setModel(new TableModelCaj());
        setTitle("Pretraga čajeva");
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCajevi = new javax.swing.JTable();
        tfName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblCajevi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(tblCajevi);

        tfName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                tfNameKeyReleased(evt);
            }
        });

        jLabel1.setText("Naziv");

        btnDetails.setText("Detalji");
        btnDetails.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDetailsActionPerformed(evt);
            }
        });

        btnDelete.setText("Obrisi");
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(53, 53, 53)
                .addComponent(btnDetails)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetails)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDetailsActionPerformed
    {//GEN-HEADEREND:event_btnDetailsActionPerformed
        int index = tblCajevi.getSelectedRow();

        if (index < 0)
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati čaj.", "", JOptionPane.INFORMATION_MESSAGE);
        }

        Caj caj = ((TableModelCaj) tblCajevi.getModel()).getCajevi().get(index);
        new InsertUpdateCajDialog(this, true, FrmMode.UPDATE, caj);
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        int index = tblCajevi.getSelectedRow();
        if (index < 0)
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati čaj.", "", JOptionPane.INFORMATION_MESSAGE);
        }

        Caj kupac = ((TableModelCaj) tblCajevi.getModel()).getCajevi().get(index);
        try
        {
            ClientController.getInstance().deleteCaj(kupac);
            JOptionPane.showMessageDialog(this, "Čaj je uspešno izbrisan.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            ((TableModelCaj) getTblCajevi().getModel()).refresh();

            MainForm mf = (MainForm) getParent();
            mf.populateCajCombo();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "GRESKA\n" + ex.getMessage(), "Poruka", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tfNameKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNameKeyReleased
    {//GEN-HEADEREND:event_tfNameKeyReleased
        String name = tfName.getText().strip();

        if (name.isEmpty())
        {
            try
            {
                List<Caj> filtered = ClientController.getInstance().getAllCaj();
                ((TableModelCaj) tblCajevi.getModel()).setCajevi(filtered);
                return;
            }
            catch (Exception ex)
            {
                Logger.getLogger(SearchCajDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try
        {
            Caj caj = new Caj();
            caj.setNaziv(name);

            List<Caj> filtered = ClientController.getInstance().filterCajevi(caj);
            ((TableModelCaj) tblCajevi.getModel()).setCajevi(filtered);
        }
        catch (Exception ex)
        {
            Logger.getLogger(SearchCajDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tfNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCajevi;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTblCajevi()
    {
        return tblCajevi;
    }
}
