/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import controller.ClientController;
import domain.Travar;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Yo
 */
public class LoginForm extends javax.swing.JFrame
{

    /**
     * Creates new form NewLogin
     */
    public LoginForm()
    {
        initComponents();

        ImageIcon originalImageIcon = new ImageIcon("images/tea_login.jpg");
        if (originalImageIcon.getImageLoadStatus() == java.awt.MediaTracker.COMPLETE)
        {
            Image image = originalImageIcon.getImage().getScaledInstance(300, 420, Image.SCALE_SMOOTH);

            ImageIcon scaledImageIcon = new ImageIcon(image);

            lblImg.setIcon(scaledImageIcon);
        }
        else
        {
            lblImg.setText("Nije pronađena slika: tea_login.jpg");
        }

        setLocationRelativeTo(null);
        setSize(576, 420);
        setResizable(false);

        lblH1.setForeground(new Color(0x7da840));

        tfUsername.putClientProperty("JTextField.placeholderText", "Unesite korisničko ime");
        tfUsername.putClientProperty("JTextField.showClearButton", true);
        tfUsername.updateUI();

        pfPass.putClientProperty("JTextField.placeholderText", "Unesite lozinku");
        pfPass.putClientProperty(FlatClientProperties.STYLE, "showRevealButton:true");

        btnLogin.putClientProperty("JButton.buttonType", "roundRect");
        btnLogin.setBackground(new Color(125, 168, 64));
        btnLogin.setForeground(Color.WHITE);
        btnLogin.setFont(new Font("SansSerif", Font.BOLD, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblH1 = new javax.swing.JLabel();
        pfPass = new javax.swing.JPasswordField();
        lblH2 = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Username:");

        btnLogin.setText("Log in");
        btnLogin.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btnLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLoginActionPerformed(evt);
            }
        });

        tfUsername.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tfUsername.setMargin(new java.awt.Insets(3, 6, 3, 6));
        tfUsername.setPreferredSize(new java.awt.Dimension(200, 28));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Password:");

        lblH1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblH1.setText("Dobrodošli!");

        pfPass.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        pfPass.setMargin(new java.awt.Insets(3, 6, 3, 6));
        pfPass.setPreferredSize(new java.awt.Dimension(200, 28));

        lblH2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblH2.setText("Ulogujte se da biste nastavili.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblH2)
                    .addComponent(lblH1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pfPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblH2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnLogin)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);
        getContentPane().add(lblImg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLoginActionPerformed
    {//GEN-HEADEREND:event_btnLoginActionPerformed
        try
        {
            String username = tfUsername.getText();
            String password = String.valueOf(pfPass.getPassword());

            Travar t = new Travar();
            t.setUsername(username);
            t.setPassword(password);

            System.out.println(t.getUsername() + " " + t.getPassword());

            t = ClientController.getInstance().login(t);
            JOptionPane.showMessageDialog(this, "Korisničko ime i šifra su ispravni.", "Login successful", JOptionPane.INFORMATION_MESSAGE);
            new MainForm(t);
            this.dispose();

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Login error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */


 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                FlatMacLightLaf.setup();

                Color fokusBoja = new Color(0x7da840);

                //UIManager.put("Component.accentColor", fokusBoja);
                UIManager.put("Component.focusColor", fokusBoja);
                UIManager.put("ComboBox.selectionBackground", fokusBoja);
                UIManager.put("MenuItem.selectionBackground", fokusBoja);

                UIManager.put("ComboBox.buttonBackground", fokusBoja);

                UIManager.put("Table.selectionBackground", fokusBoja);
                UIManager.put("Table.selectionInactiveBackground", fokusBoja);
                UIManager.put("Table.selectionInactiveForeground", 0xFFFFFF);
                UIManager.put("Table.selectionForeground", 0xFFFFFF);

                UIManager.put("TextComponent.arc", 15);
                UIManager.put("Button.hoverBorderColor", fokusBoja);

                UIManager.put("Component.focusedBorderColor", fokusBoja);
                UIManager.put("Component.showFocusBorder", false);
                UIManager.put("Button.focusedBorderColor", new Color(0, 0, 0, 0));

                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblH1;
    private javax.swing.JLabel lblH2;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
