/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.github.jozefkis.autocompletecb.AutoCompleteCBDecoratorUtils;
import forms.kupac.InsertUpdateKupacDialog;
import forms.kupac.SearchKupacDialog;
import controller.ClientController;

import domain.Caj;
import domain.Kupac;
import domain.Racun;
import domain.StavkaRacuna;
import domain.Travar;
import forms.caj.InsertUpdateCajDialog;
import forms.caj.SearchCajDialog;
import forms.racun.SearchRacunDialog;
import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelStavkeRacuna;

/**
 *
 * @author Yo
 */
public class MainForm extends javax.swing.JFrame
{

    private final Travar ulogovani;
    private double ukupno = 0;
    private final TableModelStavkeRacuna model;

    /**
     * Creates new form MainForm
     */
    public MainForm(Travar t)
    {
        ulogovani = t;
        initComponents();
        lblTest.setText(ulogovani.getIme() + " " + ulogovani.getPrezime());
        setLocationRelativeTo(null);
        ((javax.swing.JSpinner.DefaultEditor) spnrKolicina.getEditor()).getTextField().setEditable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setTitle("Glavna klijentska forma");

        tblStavke.setModel(new TableModelStavkeRacuna());
        model = (TableModelStavkeRacuna) tblStavke.getModel();
        model.addTableModelListener(e -> updateUkupno());

        prepareCombos();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        comboCajevi = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        spnrKolicina = new javax.swing.JSpinner();
        btnIzbrisiStavku = new javax.swing.JButton();
        btnDodajStavku = new javax.swing.JButton();
        comboTravari = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUkupanIznos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSacuvajRacun = new javax.swing.JButton();
        comboKupci = new javax.swing.JComboBox();
        lblTest = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitmSearchRacun = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitmAddKupac = new javax.swing.JMenuItem();
        mitmSearchKupac = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitmAddCaj = new javax.swing.JMenuItem();
        mitmSearchCaj = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Račun"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke računa"));

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblStavke.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblStavke.setFocusable(false);
        jScrollPane1.setViewportView(tblStavke);

        jLabel4.setText("Čaj");

        jLabel5.setText("Količina");

        spnrKolicina.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnIzbrisiStavku.setText("Izbrisi stavku");
        btnIzbrisiStavku.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIzbrisiStavkuActionPerformed(evt);
            }
        });

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnIzbrisiStavku)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajStavku))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCajevi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnrKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboCajevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(spnrKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzbrisiStavku)
                    .addComponent(btnDodajStavku))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        comboTravari.setPreferredSize(new java.awt.Dimension(250, 25));

        jLabel1.setText("Travar");

        jLabel2.setText("Kupac");

        tfUkupanIznos.setEditable(false);
        tfUkupanIznos.setFocusable(false);

        jLabel3.setText("Ukupan iznos (RSD)");

        btnSacuvajRacun.setText("Sačuvaj račun");
        btnSacuvajRacun.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSacuvajRacunActionPerformed(evt);
            }
        });

        comboKupci.setPreferredSize(new java.awt.Dimension(250, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvajRacun)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboKupci, 0, 287, Short.MAX_VALUE)
                                .addComponent(comboTravari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTravari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboKupci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSacuvajRacun)
                .addGap(7, 7, 7))
        );

        lblTest.setText("jLabel1");

        jMenu1.setText("Račun");

        mitmSearchRacun.setText("Pretraga računa");
        mitmSearchRacun.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mitmSearchRacunActionPerformed(evt);
            }
        });
        jMenu1.add(mitmSearchRacun);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kupac");

        mitmAddKupac.setText("Novi kupac");
        mitmAddKupac.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mitmAddKupacActionPerformed(evt);
            }
        });
        jMenu2.add(mitmAddKupac);

        mitmSearchKupac.setText("Pretraga kupaca");
        mitmSearchKupac.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mitmSearchKupacActionPerformed(evt);
            }
        });
        jMenu2.add(mitmSearchKupac);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Čaj");

        mitmAddCaj.setText("Novi čaj");
        mitmAddCaj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mitmAddCajActionPerformed(evt);
            }
        });
        jMenu3.add(mitmAddCaj);

        mitmSearchCaj.setText("Pretraga čajeva");
        mitmSearchCaj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mitmSearchCajActionPerformed(evt);
            }
        });
        jMenu3.add(mitmSearchCaj);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(lblTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        try
        {
            Travar t = ClientController.getInstance().logout(ulogovani);
            JOptionPane.showMessageDialog(this, "Bye, " + t.toString(), "Logout", JOptionPane.INFORMATION_MESSAGE);

            new LoginForm().setVisible(true);
            this.dispose();

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Logout unsucessful!\n" + ex.getMessage(), "Logout error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mitmAddKupacActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mitmAddKupacActionPerformed
    {//GEN-HEADEREND:event_mitmAddKupacActionPerformed
        new InsertUpdateKupacDialog(this, true, FrmMode.ADD);

    }//GEN-LAST:event_mitmAddKupacActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDodajStavkuActionPerformed
    {//GEN-HEADEREND:event_btnDodajStavkuActionPerformed
        Caj c = (Caj) comboCajevi.getSelectedItem();
        if (c == null)
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati caj.", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int kolicina = (int) spnrKolicina.getValue();

        StavkaRacuna sr = new StavkaRacuna();

        sr.setCaj(c);
        sr.setKolicina(kolicina);
        sr.setCena(c.getCena());
        sr.setIznos(kolicina * c.getCena());

        boolean result = ((TableModelStavkeRacuna) tblStavke.getModel()).addStavka(sr);

        if (!result)
        {
            JOptionPane.showMessageDialog(this, "Već ste dodali taj čaj", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnIzbrisiStavkuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnIzbrisiStavkuActionPerformed
    {//GEN-HEADEREND:event_btnIzbrisiStavkuActionPerformed
        int row = tblStavke.getSelectedRow();
        if (row != -1)
        {
            TableModelStavkeRacuna model = (TableModelStavkeRacuna) tblStavke.getModel();
            StavkaRacuna toRemove = model.getRacun().getStavkeRacuna().get(row);
            model.removeStavka(toRemove);
        }

    }//GEN-LAST:event_btnIzbrisiStavkuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mitmSearchKupacActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mitmSearchKupacActionPerformed
    {//GEN-HEADEREND:event_mitmSearchKupacActionPerformed
        // TODO add your handling code here:
        new SearchKupacDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mitmSearchKupacActionPerformed

    private void mitmSearchCajActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mitmSearchCajActionPerformed
    {//GEN-HEADEREND:event_mitmSearchCajActionPerformed
        // TODO add your handling code here:
        new SearchCajDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mitmSearchCajActionPerformed

    private void mitmAddCajActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mitmAddCajActionPerformed
    {//GEN-HEADEREND:event_mitmAddCajActionPerformed
        new InsertUpdateCajDialog(this, true, FrmMode.ADD).setVisible(true);
    }//GEN-LAST:event_mitmAddCajActionPerformed

    private void btnSacuvajRacunActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSacuvajRacunActionPerformed
    {//GEN-HEADEREND:event_btnSacuvajRacunActionPerformed
        Racun r = checkInputs();

        if (r == null)
        {
            return;
        }

        try
        {
            Racun racun = ClientController.getInstance().addRacun(r);
            JOptionPane.showMessageDialog(this, "Sistem je uspešno zapamtio račun.",
                    "Poruka", JOptionPane.INFORMATION_MESSAGE);
            clearInput();
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti račun!", "Greška", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnSacuvajRacunActionPerformed

    private void mitmSearchRacunActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mitmSearchRacunActionPerformed
    {//GEN-HEADEREND:event_mitmSearchRacunActionPerformed
        new SearchRacunDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mitmSearchRacunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzbrisiStavku;
    private javax.swing.JButton btnSacuvajRacun;
    private javax.swing.JComboBox comboCajevi;
    private javax.swing.JComboBox comboKupci;
    private javax.swing.JComboBox comboTravari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTest;
    private javax.swing.JMenuItem mitmAddCaj;
    private javax.swing.JMenuItem mitmAddKupac;
    private javax.swing.JMenuItem mitmSearchCaj;
    private javax.swing.JMenuItem mitmSearchKupac;
    private javax.swing.JMenuItem mitmSearchRacun;
    private javax.swing.JSpinner spnrKolicina;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField tfUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void populateTravarCombo()
    {
        try
        {
            List<Travar> all = ClientController.getInstance().getAllTravar();

            comboTravari.removeAllItems();

            for (Travar travar : all)
            {
                comboTravari.addItem(travar);
            }

            AutoCompleteCBDecoratorUtils.decorate(comboTravari, all);
            comboTravari.setSelectedItem(ulogovani);
        }
        catch (Exception ex)
        {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void populateKupacCombo()
    {
        try
        {
            List<Kupac> all = ClientController.getInstance().getAllKupac();
            comboKupci.removeAllItems();

            for (Kupac kupac : all)
            {
                comboKupci.addItem(kupac);
            }

            AutoCompleteCBDecoratorUtils.decorate(comboKupci, all);
            comboKupci.setSelectedIndex(-1);

        }
        catch (Exception e)
        {
            System.out.println("comboKupci error");
            System.out.println(e.getMessage());
        }
    }

    public void populateCajCombo()
    {
        try
        {
            List<Caj> all = ClientController.getInstance().getAllCaj();
            comboCajevi.removeAllItems();

            for (Caj caj : all)
            {
                comboCajevi.addItem(caj);
            }

            AutoCompleteCBDecoratorUtils.decorate(comboCajevi, all);
            comboCajevi.setSelectedIndex(-1);
        }
        catch (Exception e)
        {
            System.out.println("comboCaj error");
            System.out.println(e.getMessage());
        }
    }

    private Racun checkInputs()
    {
        Travar t = (Travar) comboTravari.getSelectedItem();
        Kupac k = (Kupac) comboKupci.getSelectedItem();
        Racun racun = model.getRacun();
        
        if (t == null)
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati travara!", "Greška", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (k == null)
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati kupca!", "Greška", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (racun.getStavkeRacuna() == null || racun.getStavkeRacuna().size() <= 0)
        {
            JOptionPane.showMessageDialog(this, "Račun mora imati barem jednu stavku!", "Greška", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (ukupno <= 0)
        {
            JOptionPane.showMessageDialog(this, "Cena ne sme biti <= 0.", "Greška", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        racun.setDatum(LocalDateTime.now());
        racun.setKupac(k);
        racun.setTravar(t);
        racun.setUkupanIznos(ukupno);
        
        return racun;
    }

    private void clearInput()
    {
        comboKupci.setSelectedIndex(-1);
        comboCajevi.setSelectedIndex(-1);
        spnrKolicina.setValue(1);

        ((TableModelStavkeRacuna) tblStavke.getModel()).clearStavke();
        ukupno = 0;
        tfUkupanIznos.setText("");
    }

    private void prepareCombos()
    {
        populateTravarCombo();
        populateKupacCombo();
        populateCajCombo();
    }

    private void updateUkupno()
    {
        ukupno = model.getRacun().getUkupanIznos();
        tfUkupanIznos.setText(String.format("%.2f", ukupno));
    }
}
