/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.ClientController;
import domain.Kupac;
import domain.Mesto;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yo
 */
public class NoviKupacDijalog extends javax.swing.JDialog
{
    private FrmMode currentMode;
    /**
     * Creates new form NoviKupacDijalog
     */
    public NoviKupacDijalog(java.awt.Frame parent, boolean modal, FrmMode mode)
    {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        currentMode = mode;
        prepareDialog(currentMode);
        
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfIme = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPrezime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfTelefon = new javax.swing.JTextField();
        comboMesto = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnAction = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Ime");

        jLabel5.setText("Prezime");

        jLabel1.setText("Telefon");

        jLabel3.setText("Mesto");

        btnAction.setText("Sacuvaj");
        btnAction.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionActionPerformed(evt);
            }
        });

        lblID.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAction)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblID)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(tfIme)
                            .addComponent(tfPrezime)
                            .addComponent(tfTelefon)
                            .addComponent(comboMesto, 0, 150, Short.MAX_VALUE)
                            .addComponent(tfID))
                        .addGap(113, 113, 113))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnAction)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnActionActionPerformed
    {//GEN-HEADEREND:event_btnActionActionPerformed
        Kupac k = checkInputs();
        if (k == null)
            return;
        
        System.out.println(k);
        
    }//GEN-LAST:event_btnActionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JComboBox comboMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfIme;
    private javax.swing.JTextField tfPrezime;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables

    private Kupac checkInputs()
    {
        String ime = capitalize(tfIme.getText().strip());
        String prezime = capitalize(tfPrezime.getText().strip());

        String telefon = tfTelefon.getText().strip();
        
        if (ime == null || ime.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ime ne sme biti prazno!", "Greska", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        else if (ime.length() > 30)
        {
            JOptionPane.showMessageDialog(this, "Ime ne sme imati vise od 30 karaktera!", "Greska", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        if (prezime == null || prezime.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Prezime ne sme biti prazno!", "Greska", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        else if (prezime.length() > 30)
        {
            JOptionPane.showMessageDialog(this, "Prezime ne sme imati vise od 30 karaktera!", "Greska", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        if (telefon == null || telefon.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Telefon mora biti unet!", "Greska", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        else if (ime.length() > 12)
        {
            JOptionPane.showMessageDialog(this, "Telefon ne sme imati vise od 12 karaktera!", "Greska", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        else if (!checkTelephoneFormat(telefon))
        {
            JOptionPane.showMessageDialog(this, "Pogrešan format telefona!", "Greska", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        if (!(comboMesto.getSelectedItem() instanceof Mesto))
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati mesto!", "Greska", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        Mesto m = (Mesto) comboMesto.getSelectedItem();
        
        return new Kupac(ime, prezime, telefon, m);

    }

    private String capitalize(String str)
    {
        if (str == null || str.isEmpty())
        {
            return str;
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
    
    private boolean checkTelephoneFormat(String telefon)
    {
        return telefon.matches("^06\\d{8,10}$");
    }

    private void prepareDialog(FrmMode currentMode)
    {
        tfID.setEnabled(false);
        comboMesto.removeAllItems();
        
        try
        {
            List<Mesto> all = ClientController.getInstance().getAllMesto();
            for (Mesto mesto : all)
            {
                comboMesto.addItem(mesto);
                comboMesto.setSelectedIndex(-1);
            }
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        
        
        
        if (currentMode == FrmMode.DODAJ)
        {
            tfID.setVisible(false);
            lblID.setVisible(false);
            
            btnAction.setText("Dodaj");
            setTitle("Dijalog - Novi kupac");
        }
        else if (currentMode == FrmMode.IZMENI)
        {
            btnAction.setText("Izmeni");
            setTitle("Dijalog - Izmeni kupca");
        }
        else
        {
            System.err.println("NEPOSTOJECI MODE!");
        }
    }
}
