/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.kupac;

import com.github.jozefkis.autocompletecb.AutoCompleteCBDecoratorUtils;
import controller.ClientController;
import domain.Kupac;
import domain.Mesto;
import forms.FrmMode;
import forms.MainForm;
import java.util.List;
import javax.swing.JOptionPane;
import models.TableModelKupac;

/**
 *
 * @author Yo
 */
public class InsertUpdateKupacDialog extends javax.swing.JDialog
{

    private FrmMode currentMode;
    private Kupac kupac;

    /**
     * Creates new form NoviKupacDijalog
     */
    public InsertUpdateKupacDialog(java.awt.Frame parent, boolean modal, FrmMode mode)
    {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(parent);
        currentMode = mode;
        prepareDialog();

        setVisible(true);

    }

    public InsertUpdateKupacDialog(java.awt.Dialog parent, boolean modal, FrmMode mode, Kupac kupac)
    {
        super(parent, modal);
        initComponents();

        currentMode = mode;
        this.kupac = kupac;

        prepareDialog();
        setLocationRelativeTo(null);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfIme = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPrezime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfTelefon = new javax.swing.JTextField();
        comboMesto = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnAction = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Ime");

        jLabel5.setText("Prezime");

        jLabel1.setText("Telefon");

        jLabel3.setText("Mesto");

        btnAction.setText("Sačuvaj");
        btnAction.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActionActionPerformed(evt);
            }
        });

        lblID.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAction)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblID)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(tfIme)
                            .addComponent(tfPrezime)
                            .addComponent(tfTelefon)
                            .addComponent(comboMesto, 0, 150, Short.MAX_VALUE)
                            .addComponent(tfID))
                        .addGap(113, 113, 113))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnAction)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnActionActionPerformed
    {//GEN-HEADEREND:event_btnActionActionPerformed
        Kupac k = checkInputs();
        if (k == null)
        {
            return;
        }

        if (currentMode == FrmMode.UPDATE)
        {
            try
            {
                ClientController.getInstance().updateKupac(kupac);
                JOptionPane.showMessageDialog(this, "Izmene su uspešno sačuvane.", "Poruka", JOptionPane.INFORMATION_MESSAGE);

                SearchKupacDialog pkd = (SearchKupacDialog) getParent();
                ((TableModelKupac) pkd.getTblKupci().getModel()).refresh();

                this.dispose();
            }
            catch (Exception ex)
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Greska!\n" + ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if (currentMode == FrmMode.ADD)
        {
            try
            {
                Kupac kupac = ClientController.getInstance().addKupac(k);
                int option = JOptionPane.showConfirmDialog(this, "Kupac: " + kupac.toString() + " je uspešno dodat sa ID-jem " + kupac.getIdKupac()
                        + ".\nŽelite li da dodate još jednog kupca?",
                        "Poruka", JOptionPane.YES_NO_OPTION);

                MainForm mf = (MainForm) getParent();
                mf.populateKupacCombo();

                if (option == JOptionPane.NO_OPTION)
                {
                    this.dispose();
                }
                else if (option == JOptionPane.YES_OPTION)
                {
                    clearInput();
                }
            }
            catch (Exception ex)
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Greška!\n" + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnActionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JComboBox comboMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfIme;
    private javax.swing.JTextField tfPrezime;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables

    private Kupac checkInputs()
    {
        String ime = tfIme.getText().strip();
        String prezime = tfPrezime.getText().strip();
        String telefon = tfTelefon.getText().strip().replace(" ", "");
        Object selectedItem = comboMesto.getSelectedItem();

        if (!validateIme(ime))
        {
            tfIme.setText("");
            return null;
        }
        if (!validatePrezime(prezime))
        {
            tfPrezime.setText("");
            return null;
        }
        if (!validateTelefon(telefon))
        {
            tfTelefon.setText("");
            return null;
        }
        if (!validateMesto(selectedItem))
        {
            return null;
        }

        String formattedIme = capitalize(ime);
        String formattedPrezime = capitalize(prezime);
        Mesto m = (Mesto) selectedItem;

        if (kupac != null)
        {
            kupac.setIme(formattedIme);
            kupac.setPrezime(formattedPrezime);
            kupac.setTelefon(telefon);
            kupac.setMesto(m);

            return kupac;
        }

        return new Kupac(formattedIme, formattedPrezime, telefon, m);
    }

    private void prepareDialog()
    {
        tfID.setEnabled(false);
        comboMesto.removeAllItems();

        try
        {
            List<Mesto> all = ClientController.getInstance().getAllMesto();
            for (Mesto mesto : all)
            {
                comboMesto.addItem(mesto);
            }

            AutoCompleteCBDecoratorUtils.decorate(comboMesto, all);
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }

        if (currentMode == FrmMode.ADD)
        {
            tfID.setVisible(false);
            lblID.setVisible(false);

            btnAction.setText("Dodaj");
            setTitle("Dijalog - Novi kupac");
            comboMesto.setSelectedIndex(-1);
        }
        else if (currentMode == FrmMode.UPDATE)
        {
            btnAction.setText("Izmeni");
            setTitle("Dijalog - Izmeni kupca");

            tfID.setText(String.valueOf(kupac.getIdKupac()));
            tfIme.setText(kupac.getIme());
            tfPrezime.setText(kupac.getPrezime());
            tfTelefon.setText(kupac.getTelefon());
            comboMesto.setSelectedItem(kupac.getMesto());
        }
        else
        {
            System.err.println("NEPOSTOJECI MODE!");
        }
    }

    private boolean validateIme(String ime)
    {
        if (ime == null || ime.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ime ne sme biti prazno!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (ime.length() > 30)
        {
            JOptionPane.showMessageDialog(this, "Ime ne sme imati vise od 30 karaktera!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validatePrezime(String prezime)
    {
        if (prezime == null || prezime.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Prezime ne sme biti prazno!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (prezime.length() > 30)
        {
            JOptionPane.showMessageDialog(this, "Prezime ne sme imati vise od 30 karaktera!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validateTelefon(String telefon)
    {
        if (telefon == null || telefon.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Telefon mora biti unet!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (telefon.length() > 12)
        {
            JOptionPane.showMessageDialog(this, "Telefon ne sme imati vise od 12 karaktera!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!checkTelephoneFormat(telefon))
        {
            JOptionPane.showMessageDialog(this, "Pogrešan format telefona!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validateMesto(Object obj)
    {
        if (!(obj instanceof Mesto))
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati mesto!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private String capitalize(String str)
    {
        if (str == null || str.isEmpty())
        {
            return str;
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }

    private boolean checkTelephoneFormat(String telefon)
    {
        return telefon.matches("^06\\d{8,10}$");
    }

    private void clearInput()
    {
        tfIme.setText("");
        tfPrezime.setText("");
        tfTelefon.setText("");
        comboMesto.setSelectedIndex(-1);
    }
}
