/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.kupac;

import controller.ClientController;
import domain.Kupac;
import forms.FrmMode;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelKupac;

/**
 *
 * @author Yo
 */
public class PretragaKupacaDijalog extends javax.swing.JDialog
{

    /**
     * Creates new form PretragaKupacaDijalog
     */
    public PretragaKupacaDijalog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        tblKupci.setModel(new TableModelKupac());
        setTitle("Pretraga kupaca");
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKupci = new javax.swing.JTable();
        tfImePrezime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKupci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(tblKupci);

        jLabel1.setText("Ime i prezime");

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPretraziActionPerformed(evt);
            }
        });

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnPretrazi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnObrisi)
                .addGap(53, 53, 53)
                .addComponent(btnDetalji)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalji)
                    .addComponent(btnObrisi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPretraziActionPerformed
    {//GEN-HEADEREND:event_btnPretraziActionPerformed
        String imePrezime = tfImePrezime.getText().strip();

        if (imePrezime.isEmpty())
        {
            try
            {
                List<Kupac> filtered = ClientController.getInstance().getAllKupac();
                ((TableModelKupac) tblKupci.getModel()).setKupci(filtered);
                return;
            }
            catch (Exception ex)
            {
                Logger.getLogger(PretragaKupacaDijalog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try
        {
            List<Kupac> filtered = ClientController.getInstance().filterKupci(new Kupac());
            ((TableModelKupac) tblKupci.getModel()).setKupci(filtered);
        }
        catch (Exception ex)
        {
            Logger.getLogger(PretragaKupacaDijalog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDetaljiActionPerformed
    {//GEN-HEADEREND:event_btnDetaljiActionPerformed
        int index = tblKupci.getSelectedRow();
        
        if (index < 0)
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati kupca.", "", JOptionPane.INFORMATION_MESSAGE);
        }
        
        Kupac kupac = ((TableModelKupac) tblKupci.getModel()).getKupci().get(index);
        new InsertUpdateKupacDijalog(this, true, FrmMode.UPDATE, kupac);
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnObrisiActionPerformed
    {//GEN-HEADEREND:event_btnObrisiActionPerformed
        int index = tblKupci.getSelectedRow();
        if (index < 0)
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati kupca.", "", JOptionPane.INFORMATION_MESSAGE);
        }
        
        Kupac kupac = ((TableModelKupac) tblKupci.getModel()).getKupci().get(index);
        try
        {
            ClientController.getInstance().deleteKupac(kupac);
            JOptionPane.showMessageDialog(this, "Kupac je uspešno izbrisan.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            ((TableModelKupac) getTblKupci().getModel()).refresh();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "GRESKA\n" + ex.getMessage(), "Poruka", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKupci;
    private javax.swing.JTextField tfImePrezime;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTblKupci()
    {
        return tblKupci;
    }
}
