/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.kupac;

import controller.ClientController;
import domain.Kupac;
import forms.FrmMode;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.TableModelKupac;

/**
 *
 * @author Yo
 */
public class SearchKupacDialog extends javax.swing.JDialog
{

    /**
     * Creates new form PretragaKupacaDijalog
     */
    public SearchKupacDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        tblKupci.setModel(new TableModelKupac());
        setTitle("Pretraga kupaca");
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKupci = new javax.swing.JTable();
        tfFirstLastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKupci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblKupci.setFocusable(false);
        jScrollPane1.setViewportView(tblKupci);

        tfFirstLastName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                tfFirstLastNameKeyReleased(evt);
            }
        });

        jLabel1.setText("Ime i prezime");

        btnDetails.setText("Detalji");
        btnDetails.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDetailsActionPerformed(evt);
            }
        });

        btnDelete.setText("Obrisi");
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tfFirstLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(53, 53, 53)
                .addComponent(btnDetails)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFirstLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetails)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDetailsActionPerformed
    {//GEN-HEADEREND:event_btnDetailsActionPerformed
        int index = tblKupci.getSelectedRow();

        if (index < 0)
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati kupca.", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Kupac kupac = ((TableModelKupac) tblKupci.getModel()).getKupci().get(index);
        new InsertUpdateKupacDialog(this, true, FrmMode.UPDATE, kupac);
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        int index = tblKupci.getSelectedRow();
        if (index < 0)
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati kupca.", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Kupac kupac = ((TableModelKupac) tblKupci.getModel()).getKupci().get(index);
        try
        {
            ClientController.getInstance().deleteKupac(kupac);
            JOptionPane.showMessageDialog(this, "Sistem je uspešno obrisao kupca.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            ((TableModelKupac) getTblKupci().getModel()).refresh();
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sistem ne može da obriše kupca.", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tfFirstLastNameKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfFirstLastNameKeyReleased
    {//GEN-HEADEREND:event_tfFirstLastNameKeyReleased
        // TODO add your handling code here:
        String imePrezime = tfFirstLastName.getText().strip();

        if (imePrezime.isEmpty())
        {
            try
            {
                List<Kupac> filtered = ClientController.getInstance().getAllKupac();
                ((TableModelKupac) tblKupci.getModel()).setKupci(filtered);
                return;
            }
            catch (Exception ex)
            {
                Logger.getLogger(SearchKupacDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try
        {
            String[] arr = imePrezime.split(" ");
            Kupac k = new Kupac();
            if (arr.length == 2)
            {
                k.setIme(arr[0]);
                k.setPrezime(arr[1]);
            }
            else
            {
                k.setIme(arr[0]);
                k.setPrezime("");
            }

            SwingUtilities.invokeLater(() ->
            {
                try
                {
                    List<Kupac> filtered = ClientController.getInstance().filterKupci(k);
                    ((TableModelKupac) tblKupci.getModel()).setKupci(filtered);
                }
                catch (Exception ex)
                {
                    Logger.getLogger(SearchKupacDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            });
        }
        catch (Exception ex)
        {
            Logger.getLogger(SearchKupacDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tfFirstLastNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKupci;
    private javax.swing.JTextField tfFirstLastName;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTblKupci()
    {
        return tblKupci;
    }
}
