/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.racun;

import controller.ClientController;
import com.github.jozefkis.autocompletecb.AutoCompleteCBDecoratorUtils;
import domain.Caj;
import domain.Racun;
import domain.StavkaRacuna;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import models.TableModelStavkeRacuna;

/**
 *
 * @author jozef
 */
public class RacunDetailsDialog extends javax.swing.JDialog
{

    private final Racun ogRacun;
    private final TableModelStavkeRacuna model;

    /**
     * Creates new form RacunDetailsDialog
     *
     * @param parent
     * @param modal
     * @param racun
     */
    public RacunDetailsDialog(java.awt.Dialog parent, boolean modal, Racun racun)
    {
        super(parent, modal);
        initComponents();

        this.ogRacun = racun;
        tblStavke.setModel(new TableModelStavkeRacuna(ogRacun));
        model = (TableModelStavkeRacuna) tblStavke.getModel();
        model.addTableModelListener(e -> updateUkupno());

        TableRowSorter<TableModelStavkeRacuna> sorter = new TableRowSorter<>(model);
        sorter.setRowFilter(new RowFilter<TableModelStavkeRacuna, Integer>()
        {
            @Override
            public boolean include(RowFilter.Entry<? extends TableModelStavkeRacuna, ? extends Integer> entry)
            {
                TableModelStavkeRacuna m = entry.getModel();
                StavkaRacuna s = m.getStavkaAt(entry.getIdentifier());
                return !"DB_DELETE".equals(s.getStatus());
            }

        });
        tblStavke.setRowSorter(sorter);

        prepareView();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        pnlStavke = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        comboCaj = new javax.swing.JComboBox();
        spnrKolicina = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        btnAddStavka = new javax.swing.JButton();
        lblCaj = new javax.swing.JLabel();
        btnDeleteStavka = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTravar = new javax.swing.JLabel();
        lblKupac = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlStavke.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stavke računa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 13))); // NOI18N

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStavke.setFocusable(false);
        jScrollPane1.setViewportView(tblStavke);

        spnrKolicina.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel6.setText("Količina");

        btnAddStavka.setText("Dodaj stavku");
        btnAddStavka.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddStavkaActionPerformed(evt);
            }
        });

        lblCaj.setText("Čaj");

        btnDeleteStavka.setText("Obrisi stavku");
        btnDeleteStavka.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteStavkaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStavkeLayout = new javax.swing.GroupLayout(pnlStavke);
        pnlStavke.setLayout(pnlStavkeLayout);
        pnlStavkeLayout.setHorizontalGroup(
            pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkeLayout.createSequentialGroup()
                .addGroup(pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStavkeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStavkeLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblCaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCaj, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnrKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnAddStavka, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStavkeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDeleteStavka, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlStavkeLayout.setVerticalGroup(
            pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStavkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnrKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(pnlStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCaj)))
                    .addComponent(btnAddStavka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteStavka)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel1.setText("Broj računa:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel2.setText("Datum kreiranja:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel3.setText("Travar:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel4.setText("Kupac:");

        lblID.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblID.setText("id");

        lblDate.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblDate.setText("date");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel5.setText("Ukupan iznos:");

        lblTravar.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblTravar.setText("trvr");

        lblKupac.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblKupac.setText("Kpc");

        lblTotal.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblTotal.setText("1,800.50");

        btnSave.setText("Sačuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Odustani");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(lblTravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKupac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTravar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblKupac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addComponent(pnlStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStavkaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddStavkaActionPerformed
    {//GEN-HEADEREND:event_btnAddStavkaActionPerformed
        if (!(comboCaj.getSelectedItem() instanceof Caj))
        {
            JOptionPane.showMessageDialog(this, "Morate izabrati čaj.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Caj c = (Caj) comboCaj.getSelectedItem();
        int kolicina = (int) spnrKolicina.getValue();

        StavkaRacuna sr = new StavkaRacuna();

        sr.setCaj(c);
        sr.setKolicina(kolicina);
        sr.setCena(c.getCena());
        sr.setIznos(kolicina * c.getCena());
        sr.setRacun(ogRacun);
        sr.setStatus("DB_INSERT");

        boolean result = model.addStavka(sr);

        if (!result)
        {
            JOptionPane.showMessageDialog(this, "Već ste dodali taj čaj", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        ogRacun.setDatum(LocalDateTime.now());
        DateTimeFormatter customFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        lblDate.setText(String.valueOf(ogRacun.getDatum().toLocalDate().format(customFormatter))
                + ", " + ogRacun.getDatum().toLocalTime().truncatedTo(ChronoUnit.SECONDS));
    }//GEN-LAST:event_btnAddStavkaActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        try
        {
            ogRacun.setDatum(LocalDateTime.now());
            ClientController.getInstance().updateRacun(ogRacun);
            JOptionPane.showMessageDialog(this, "Sistem je uspešno zapamtio račun.", "Uspešno ažuriranje", JOptionPane.INFORMATION_MESSAGE);
            ((SearchRacunDialog) this.getParent()).refreshTable();
            this.dispose();
        }
        catch (Exception ex)
        {
            System.out.println("GREKSA: " + ex.getMessage() + "\n");
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti račun.", "Greška", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        ((SearchRacunDialog) this.getParent()).refreshTable();
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteStavkaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteStavkaActionPerformed
    {//GEN-HEADEREND:event_btnDeleteStavkaActionPerformed
        int viewRow = tblStavke.getSelectedRow();
        if (viewRow == -1)
        {
            JOptionPane.showMessageDialog(this, "Izaberite stavku za brisanje.");
            return;
        }

        int modelRow = tblStavke.convertRowIndexToModel(viewRow);

        StavkaRacuna toDelete = model.getRacun().getStavkeRacuna().get(modelRow);

        if ("DB_INSERT".equals(toDelete.getStatus()))
            model.removeStavka(toDelete);
        else
            model.deleteStavka(toDelete);
        
        ogRacun.setDatum(LocalDateTime.now());
        DateTimeFormatter customFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        lblDate.setText(String.valueOf(ogRacun.getDatum().toLocalDate().format(customFormatter))
                + ", " + ogRacun.getDatum().toLocalTime().truncatedTo(ChronoUnit.SECONDS));
    }//GEN-LAST:event_btnDeleteStavkaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStavka;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteStavka;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboCaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaj;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblKupac;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTravar;
    private javax.swing.JPanel pnlStavke;
    private javax.swing.JSpinner spnrKolicina;
    private javax.swing.JTable tblStavke;
    // End of variables declaration//GEN-END:variables

    private void prepareView()
    {
        populateCajCombo();

        DateTimeFormatter customFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        lblID.setText(String.valueOf(ogRacun.getIdRacun()));
        lblDate.setText(String.valueOf(ogRacun.getDatum().toLocalDate().format(customFormatter)) + ", " + ogRacun.getDatum().toLocalTime());
        lblTravar.setText(ogRacun.getTravar().toString());
        lblKupac.setText(ogRacun.getKupac().toString());
        lblTotal.setText(String.valueOf(ogRacun.getUkupanIznos()));

        if (ogRacun.getDatum().plusDays(3L).isBefore(LocalDateTime.now()))
        {
            btnAddStavka.setEnabled(false);
            btnSave.setEnabled(false);
            tblStavke.setEnabled(false);
            btnDeleteStavka.setEnabled(false);
        }

    }

    private void populateCajCombo()
    {
        try
        {
            List<Caj> all = ClientController.getInstance().getAllCaj();
            comboCaj.removeAllItems();

            for (Caj caj : all)
            {
                comboCaj.addItem(caj);
            }

            AutoCompleteCBDecoratorUtils.decorate(comboCaj, all);
            comboCaj.setSelectedIndex(-1);
        }
        catch (Exception e)
        {
            System.out.println("comboCaj error");
            System.out.println(e.getMessage());
        }
    }

    private void updateUkupno()
    {
        double ukupno = model.getRacun().getUkupanIznos();
        lblTotal.setText(String.format("%.2f", ukupno));
        System.out.println(ogRacun.getUkupanIznos());
    }
}
