/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.racun;

import controller.ClientController;
import dev.jozefkis.swingutils.decorators.AutoCompleteCBDecoratorUtils;
import domain.Kupac;
import domain.Racun;
import domain.Travar;
import java.util.List;
import models.TableModelRacun;

/**
 *
 * @author SOFIJA
 */
public class SearchRacunDialog extends javax.swing.JDialog
{

    /**
     * Creates new form SearchRacunDialog
     */
    public SearchRacunDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        prepareDialog();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        comboTravar = new javax.swing.JComboBox();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRacuni = new javax.swing.JTable();
        checkTravar = new javax.swing.JCheckBox();
        comboKupac = new javax.swing.JComboBox();
        checkKupac = new javax.swing.JCheckBox();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSearch.setText("Pretraga");
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        tblRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRacuni.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblRacuni);

        checkTravar.setText("Travar");
        checkTravar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkTravarActionPerformed(evt);
            }
        });

        checkKupac.setText("Kupac");
        checkKupac.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkKupacActionPerformed(evt);
            }
        });

        btnDetails.setText("Detalji");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkTravar)
                            .addComponent(checkKupac))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboTravar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(comboKupac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTravar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkTravar))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkKupac))
                .addGap(26, 26, 26)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDetails)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchActionPerformed
    {//GEN-HEADEREND:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Racun r = new Racun();
        if (comboTravar.getSelectedItem() instanceof Travar)
        {
            r.setTravar((Travar) comboTravar.getSelectedItem());
        }
        else
        {
            r.setTravar(null);
        }

        if (comboKupac.getSelectedItem() instanceof Kupac)
        {
            r.setKupac((Kupac) comboKupac.getSelectedItem());
        }
        else
        {
            r.setKupac(null);
        }

        try
        {
            List<Racun> filtered = ClientController.getInstance().getAllRacun(r);
            ((TableModelRacun) tblRacuni.getModel()).setRacuni(filtered);
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void checkTravarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkTravarActionPerformed
    {//GEN-HEADEREND:event_checkTravarActionPerformed
        // TODO add your handling code here:
        if (checkTravar.isSelected())
            comboTravar.setEnabled(true);
        else
        {
            comboTravar.setEnabled(false);
            comboTravar.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_checkTravarActionPerformed

    private void checkKupacActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkKupacActionPerformed
    {//GEN-HEADEREND:event_checkKupacActionPerformed
        // TODO add your handling code here:
        if (checkKupac.isSelected())
            comboKupac.setEnabled(true);
        else
        {
            comboKupac.setEnabled(false);
            comboKupac.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_checkKupacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox checkKupac;
    private javax.swing.JCheckBox checkTravar;
    private javax.swing.JComboBox comboKupac;
    private javax.swing.JComboBox comboTravar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRacuni;
    // End of variables declaration//GEN-END:variables

    private void prepareDialog()
    {
        populateComboTravar();
        populateComboKupac();
        loadTableData();
        checkTravar.setSelected(false);
        checkKupac.setSelected(false);
    }

    private void populateComboTravar()
    {
        try
        {
            comboTravar.removeAllItems();
            List<Travar> all = ClientController.getInstance().getAllTravar();

            for (Travar t : all)
            {
                comboTravar.addItem(t);
            }

            comboTravar.setEnabled(false);
            AutoCompleteCBDecoratorUtils.decorate(comboTravar, all);
            comboTravar.setSelectedIndex(-1);

        }
        catch (Exception ex)
        {
            System.getLogger(SearchRacunDialog.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    private void loadTableData()
    {
        try
        {
            List<Racun> all = ClientController.getInstance().getAllRacun(new Racun());
            tblRacuni.setModel(new TableModelRacun(all));
            
            tblRacuni.getColumnModel().getColumn(2).setPreferredWidth(150);
        }
        catch (Exception ex)
        {
            System.getLogger(SearchRacunDialog.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    private void populateComboKupac()
    {
        try
        {
            comboKupac.removeAllItems();
            List<Kupac> all = ClientController.getInstance().getAllKupac();

            for (Kupac k : all)
            {
                comboKupac.addItem(k);
            }

            comboKupac.setEnabled(false);
            AutoCompleteCBDecoratorUtils.decorate(comboKupac, all);
            comboKupac.setSelectedIndex(-1);

        }
        catch (Exception ex)
        {
            System.getLogger(SearchRacunDialog.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
}
